version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - quendap-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/quendap?allowPublicKeyRetrieval=true
      - spring.datasource.username=admin
      - spring.datasource.password=admin
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - quendap-net
    environment:
      MYSQL_DATABASE: quendap
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
networks:
  quendap-net: